config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'contact', to: 'static_pages#contact'
  get 'team', to: 'static_pages#team'
  get 'welcome/:user_entry', to: 'welcome#show'
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities
  resources :users  
  resources :gossips do
    resources :comments
    resources :likes
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :jointablegossiptags
  has_many :tags, through: :jointablegossiptags
  has_many :likes

  validates :title,
    presence: true,
    length: { in: 3..14 }

  validates :content,
    presence: true

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @gossips = Gossip.all
    @gossips = @gossips.sort_by {|obj| obj.id}

    @comments = Comment.all
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    puts "#" * 60
    puts "Inside gossips controller:"
    puts  @gossip_id = params[:id]
    puts "#" * 60
    @gossips = Gossip.all
    @comments = Comment.all
    
    @gossip = @gossips.find(@gossip_id)
    user = User.find_by(id: session[:user_id])
    p @user_likes = Like.where(gossip: @gossip, user: user)
    @like = @user_likes[0]
    
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    puts "$" * 60
    puts "ceci est le contenu de params :"
    puts params
    puts "$" * 60

    @gossip = Gossip.new(title: params[:gossip_title], content: params[:gossip_content]) 
    @gossip.user = User.find_by(id: session[:user_id])

    if @gossip.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      flash[:Notice] = "Potin créé avec succès"
      redirect_to :root
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      flash.now[:notice] = @gossip.errors.full_messages
      render :new
    end
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossip.find(params[:id])

    unless current_user == @gossip.user
      flash[:danger] = "Action impossible"
      redirect_to @gossip
    end
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    @gossip = Gossip.find(params[:id])

    unless current_user == @gossip.user
      flash[:danger] = "Action impossible"
      redirect_to @gossip
    end

    puts "GO" * 60
    puts "Gossip controller, update method:"
    puts params
    puts "GO" * 60

    if @gossip.update(title: params[:gossip_title], content: params[:gossip_content])
      flash[:Notice] = "Potin modifié avec succès"
      redirect_to @gossip
    else
      flash.now[:notice] = @gossip.errors.full_messages
      render :edit
    end

  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossip = Gossip.find(params[:id])

    unless current_user == @gossip.user
      flash[:danger] = "Action impossible"
      redirect_to @gossip
    end
    
    @gossip.destroy

    puts "GO" * 60
    puts "Gossip controller, destroy method:"
    puts params
    puts "GO" * 60

    if @gossip.destroy
      flash[:Notice] = "Potin supprimé avec succès"
      redirect_to :root
    else
      flash.now[:notice] = "did not work"
      render @gossip
    end
  
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>

     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    body {
        background-image: url('https://media.istockphoto.com/vectors/bright-pink-and-blue-versus-retro-comic-background-vector-id1150984736?k=6&m=1150984736&s=612x612&w=0&h=kecGH2luUl_P2LQLs4zbbPSs7zyOyzE0l1k9CwjlBWs=');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }

    #connection {
        background-color: #FFAB00;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 10%;
        padding: 5%;
        border-radius: 20px;
    }

        #title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

<div class = "mt-5 mx-3">
    

    <div>
        <% flash.each do |msg| %>
        <div class="alert alert-danger">
            <%= msg.join(": ").html_safe %>
                
        </div>
        <% end %>
        
        <div id="connection">
            <div>
                <h1 class="mb-4 pb-4" id="title">Editer le potin</h1>
            <div>

            <%= form_tag url_for(action: 'update'), method: "patch" do %>

                <h4><%= label_tag 'Titre' %></h4>
                <%= text_field_tag 'gossip_title', @gossip.title %>
                <br /> <br />

                <h4><%= label_tag 'Contenu' %></h4>
                <%= text_field_tag 'gossip_content', @gossip.content %>
                <br /> <br /> <br />

                <%= submit_tag("Enregistrer mon Potin", :class=>"btn btn-danger") %>
            <% end %>
        </div>

    </div>
</div>

    <%# <script>

    document.body.style.background = "#"+((1<<24)*Math.random()|0).toString(16);
    </script> %>


  </body>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', async: Rails.env.production?, :cache => 'cached/all' %>

</html>

app/views/gossips/index.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
                body {
                font-family: Arial, Helvetica, sans-serif;
                }

                .flip-card {
                background-color: transparent;
                width: 300px;
                height: 300px;
                perspective: 1000px;
                }

                .flip-card-inner {
                position: relative;
                width: 100%;
                height: 100%;
                text-align: center;
                transition: transform 0.6s;
                transform-style: preserve-3d;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

                .flip-card:hover .flip-card-inner {
                transform: rotateY(180deg);
                }

                .flip-card-front, .flip-card-back {
                position: absolute;
                width: 100%;
                height: 100%;
                -webkit-backface-visibility: hidden;
                backface-visibility: hidden;
                }

                .flip-card-front {
                background-color: #bbb;
                color: black;
                }

                .flip-card-back {
                background-color: #2980b9;
                color: white;
                transform: rotateY(180deg);
                }
            </style>
        </head>

    <body>
        <div class = "mt-5 mx-5">
            <h1><%= link_to "Créer un potin", new_gossip_path, class: "btn btn-secondary btn-lg text-light mt-3" %></h1>

            <div class="row">

                <% @gossips.map do |gossip| %>
                    <div class="col-12 col-sm-4 my-3 flip-card border-success">
                        <div class="flip-card-inner">
                            <div class="flip-card-front bg-light d-flex flex-column">
                                <div class="card-header text-center pb-1 text-white bg-info">
                                    <h5>Gossip nº <%=gossip.id%></h5>
                                </div>
                                <div class="my-auto">
                                    <h2 class="card-title text-warning py-2">By <%=gossip.user.first_name%></h2>
                                    <h4 class="card-text text-info"><%=gossip.title%></h4>
                                    <h4 class="text-info">Nombre de coms - <%= Comment.where(gossip: gossip).count%></h4>
                                    <h4 class="text-info">Nombre de likes - <%= Like.where(gossip: gossip).count%></h4>
                                </div>
                            </div>

                            <div class="flip-card-back d-flex flex-column bg-white">
                                <div class="card-header text-center pb-1 text-wh bg-info">
                                    <h5>Gossip nº <%=gossip.id%></h5>
                                </div>
                                <div class="my-auto">
                                    <p><%= link_to "Voir plus", gossip_path(gossip.id), class: "btn btn-success btn-lg"%></p>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>



    </body>


</html>

app/views/gossips/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>

     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    body {
        background-image: url('https://media.istockphoto.com/vectors/bright-pink-and-blue-versus-retro-comic-background-vector-id1150984736?k=6&m=1150984736&s=612x612&w=0&h=kecGH2luUl_P2LQLs4zbbPSs7zyOyzE0l1k9CwjlBWs=');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }

    #connection {
        background-color: #FFAB00;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 10%;
        padding: 5%;
        border-radius: 20px;
    }

    #title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

<div class = "mt-5 mx-3">
    

    <div>
        <% flash.each do |msg| %>
        <div class="alert alert-danger">
            <%= msg.join(": ").html_safe %>
                
        </div>
        <% end %>
        
        <div id="connection">
            <div>
                <h1 class="mb-4 pb-4" id="title">Création d'un potin</h1>
            <div>

            <%= form_tag url_for(action: 'create'), method: "post" do %>

                <h4><%= label_tag 'Titre de mon potin' %></h4>
                <%= text_field_tag 'gossip_title' %>
                <br /> <br />

                <h4><%= label_tag 'Contenu de mon potin' %></h4>
                <%= text_area_tag 'gossip_content' %>
                <br /> <br /> <br />

                <%= submit_tag("Enregistrer mon Potin", :class=>"btn btn-danger") %>
            <% end %>
        </div>

    </div>
</div>

    <%# <script>

    document.body.style.background = "#"+((1<<24)*Math.random()|0).toString(16);
    </script> %>


  </body>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', async: Rails.env.production?, :cache => 'cached/all' %>

</html>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>

     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    body {
        background-image: url('https://media.istockphoto.com/vectors/yellow-and-orange-retro-comic-background-vector-illustration-vector-id1048223560?k=6&m=1048223560&s=612x612&w=0&h=M2BkRK_uV8brJgDX2TfTFNq2UwP_h-ldn33clRtJaVg=');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }

    .carte {
        background-color: #FF99D1;
        text-align: center;
        margin-left: 35%;
        margin-right: 35%;
        margin-top: 5%;
        padding: 2%;
        padding-top: 2%;
        border-radius: 20px;
    }

    .title {
        font-size: 60px;
        color: white;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

<div class = "mt-5 mx-3">
    

    <div>
        <% flash.each do |msg| %>
        <div class="alert alert-success">
            <%= msg.join(": ").html_safe %>
                
        </div>
        <% end %>
        
        <div class="carte">
            <div>
                <h1 class = "mb-3 title">Gossip nº<%=@gossip_id%></h1>
                <p>
                    <span class = "font-weight-bold">Titre</span> : <%=@gossip.title%></br>
                    <span class = "font-weight-bold">Contenu</span> : <%=@gossip.content%></br>
                    <span class = "font-weight-bold">Auteur</span> : <%=@gossip.user.first_name%> <%=@gossip.user.last_name%> 
                    <span class = "font-weight-bold">de</span> <%= link_to @gossip.user.city.name, city_path(@gossip.user.city.id) %></br>
                    <span class = "font-weight-bold text-primary"><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></span></br>
                </p>
                <p>
                    <span class = "font-weight-bold"> Potin créé le</span> : <%=@gossip.created_at%> <br />
                    <span class = "font-weight-bold"> Potin mis à jour le</span> : <%=@gossip.updated_at%> 
                </p>
            </div>

            <% if current_user == @gossip.user %>
            <div>
                <p>
                    <%= link_to "Modifier le potin", edit_gossip_path, class: "btn btn-info text-light"%>
                    <%= link_to "Supprimer le potin", gossip_path(@gossip.id), method: :delete, class: "btn btn-danger text-light" %><br/>
                    <%= link_to "Ajouter un commentaire", new_gossip_comment_path(@gossip.id), class: "btn btn-dark text-light mt-2" %>
                    
                    <% if @like != nil %>
                    <%= link_to "DisLiker le potin", gossip_like_path(@gossip.id, @like.id), method: :delete, class: "btn btn-info text-light mt-2" %></h6>
                    <% else %>
                    <%= link_to "Liker le potin", gossip_likes_path(@gossip.id), method: :post, class: "btn btn-warning mt-2" %>
                    <% end %>
                </p>
            </div>

            <% else %>
            <div>
                <p>
                    <%= link_to "Ajouter un commentaire", new_gossip_comment_path(@gossip.id), class: "btn btn-dark text-light mt-2" %>
                    <% if @like != nil %>
                    <%= link_to "DisLiker le potin", gossip_like_path(@gossip.id, @like.id), method: :delete, class: "btn btn-info text-light mt-2" %></h6>
                    <% else %>
                    <%= link_to "Liker le potin", gossip_likes_path(@gossip.id), method: :post, class: "btn btn-warning mt-2" %>
                    <% end %>
                </p>
            </div>
            <% end %>
            <div>
                <h5><%= link_to "A propos de l'auteur", user_path(@gossip.user.id)%></h5>
            </div>

            <div>
                <h3 class = "font-weight-bold mb-3 mt-4 text-white "> Commentaires :</h3>  
                <p>
                    <% @comments.where(gossip: @gossip).map do |com| %>
                    <%current_user == com.user ? com.user.first_name = "Tu" : com.user.first_name %>
                    <span class="font-weight-bold">></span> <%= com.user.first_name%> as commenté "<span class="font-weight-bold"><%= com.content%></span>" le <%= com.updated_at%></>
                </p>
                <% if current_user == com.user %>
                    <%= link_to "Editer le com", edit_gossip_comment_path(@gossip.id, com.id), class: "btn btn-info text-light" %>
                    <%= link_to "Supprimer le com", gossip_comment_path(@gossip.id, com.id), method: :delete, class: "btn btn-danger text-light" %>
                </p>
                <% end %>
            <% end %>

            </div>






        </div>


    </div>
</div>

    <%# <script>

    document.body.style.background = "#"+((1<<24)*Math.random()|0).toString(16);
    </script> %>


  </body>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', async: Rails.env.production?, :cache => 'cached/all' %>

</html>