config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'contact', to: 'static_pages#contact'
  get 'team', to: 'static_pages#team'
  get 'welcome/:user_entry', to: 'welcome#show'
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities
  resources :users  
  resources :gossips do
    resources :comments
    resources :likes
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, 
    presence: true

  validates :zip_code,
    presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content,
    presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :jointablegossiptags
  has_many :tags, through: :jointablegossiptags
  has_many :likes

  validates :title,
    presence: true,
    length: { in: 3..14 }

  validates :content,
    presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :like,
    presence: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :jointablegossiptags
  has_many :gossips, through: :jointablegossiptags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :likes
  has_secure_password


  validates :first_name,
    presence: true

  validates :last_name,
    presence: true

  validates :email,
    presence: true,
    uniqueness: true

  validates :age,
    presence: true,
    numericality: { greater_than_or_equal_to: 18 }

  validates :password,
    presence: true,
    length: { in: 6..20 }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user

  def index
    puts "@" * 60
    puts "Inside Home controller"
    puts "@" * 60

    @gossips = Gossip.all
    @gossips = @gossips.sort_by {|obj| obj.id}

  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    user = User.find_by(id: session[:user_id])
    @gossip = Gossip.find(params[:gossip_id])
    @user_likes = Like.where(gossip: @gossip, user: user)
  
    @like = Like.new(like: true, user: user, gossip: @gossip)

    if current_user == user && @user_likes.count == 0
      @like.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      flash[:Notice] = "You liked this gossip"
      redirect_to @gossip

    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      flash.now[:notice] = "Action impossible"
      redirect_to @gossip
    end
  end


  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    user = User.find_by(id: session[:user_id])
    @user_likes = Like.where(gossip: @gossip, user: user)
    @like = @user_likes[0]
 

    if current_user == user && @user_likes.count == 1
      @like.destroy # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      flash[:Notice] = "You removed your like from this gossip"
      redirect_to @gossip

    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      flash.now[:notice] = "Action impossible"
      redirect_to @gossip
    end
  
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>

     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <style>
    body {
      background-color: #fef555;
    }
  </style>    

  </head>

  <body>
    <%= yield %>

  <!-- Navbar session on -->
    <% if current_user != nil %>
    <div class="bg-dark fixed-top">
      <div class="container-fluid">
        <div class="row">
          <nav class="col navbar navbar-expand-lg navbar-dark bg-info">
            <h4 class="mr-4 mt-2 py-1"><%= link_to "The Gossip Project", root_path, class: "text-light font-weight-bold ml-3" %></h4>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarContent" class="collapse navbar-collapse justify-content-between">
              <ul class="navbar-nav mt-1">
                <li class="nav-item active mr-4 mt-2">
                  <%= link_to "Accueil", root_path, class:"text-light" %>
                </li>
                <li class="nav-item active mr-3 mt-2">
                  <%= link_to "La Team", team_path, class:"text-light" %>
                </li>
                <li class="nav-item dropdown mr-3">
                  <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Potins
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "Consulter les potins", gossips_path, class:"dropdown-item text-dark" %>
                     <%= link_to "Créer un potin", new_gossip_path, class:"dropdown-item text-dark" %>
                  </div>
                </li>
                <li class="mt-2">
                  <%= link_to "Nous contacter", contact_path, class:"text-light" %>
                </li>
              </ul>

              <h3><%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "btn btn-danger text-light mt-2 mr-3" %></h3>

            </div>
          </nav>
        </div>
      </div>
    </div>
    <!-- Navbar session on-->


    <!-- Navbar session off-->
    <% else %>
    <div class="bg-dark fixed-top">
      <div class="container-fluid">
        <div class="row">
          <nav class="col navbar navbar-expand-lg navbar-dark bg-info">
            <h4 class="mr-4 mt-2 py-1 text-light font-weight-bold ml-3">The Gossip Project</h4>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarContent" class="collapse navbar-collapse justify-content-between">
              <ul class="navbar-nav mt-1">
              </ul>
              <div class="dropdown navbar-nav mt-2 mr-3 d-flex justify-content-end">
                <a class="btn btn-light text-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Connection
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to "S'inscrire", new_user_path, class:"dropdown-item" %>
                  <%= link_to "Se connecter", new_session_path, class:"dropdown-item" %>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
    <% end %>
    <!-- Navbar -->

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>



    <script>

    // document.body.style.background = "#"+((1<<24)*Math.random()|0).toString(16);
    </script>


  </body>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', async: Rails.env.production?, :cache => 'cached/all' %>

</html>